### PR TITLE
Show semi-opaque white background for dark mode

### PR DESCRIPTION
**Pull request by JackHowa**
This is in response to issue #10 with Twitter and YouTube dark modes causing non-legible text on hover and on text show. 

As a suggestion, I used a semi-opaque white for background. In this way, white mode and dark mode show a highlight. I'm open to other UI style fixes.

before:
Screen Shot 2019-10-05 at 8 44 17 PM

*legibility issue*
Screen Shot 2019-10-05 at 8 44 06 PM

after: 
Screen Shot 2019-10-05 at 8 32 10 PM
Screen Shot 2019-10-05 at 8 32 01 PM

### CODE REVIEW

**Comment by JackHowa** [comment]
@googlebot I signed it!

**Comment by rachelrosengoogle** [comment]
Hi Jack,

Thanks for your contribution. I started looking at this a bit more and I think that we may not actually need this background-color set on hover at all for comments that have not been hidden by tune, to white or a semi-opaque white at all, since the default behavior on YouTube doesn't have any change in background color on hover and we use an outline for Tuned comments on hover. I can't recall if the default behavior for this was different at the time we initially created Tune, or if this is a remnant of an earlier design where we changed the background color of Tuned comments on YouTube to a light gray like we do for Twitter and Reddit. 

In a quick test, I tried removing the background color setting without replacing it with anything, and this appeared to work with both light and dark mode on YouTube, and sort of for reddit (though there are some aspects to dark mode that still don't work nicely). Would you mind checking if this works for dark mode on the other sites? For the non-YouTube sites we have the "hover" UI for comments filtered by Tune to be a change in background color to a light gray, so that could be where the default white background setting came from.

**Comment by JackHowa** [comment]
>  I started looking at this a bit more and I think that we may not actually need this background-color set on hover at all for comments that have not been hidden by tune, to white or a semi-opaque white at all, since the default behavior on YouTube doesn't have any change in background color on hover and we use an outline for Tuned comments on hover.

Totally agree. I like your solution and thinking on this. Haven't seen any issues with Disqus.

**Comment by JackHowa** [comment]
Updated the branch deleting the hover and background style. For clarity, I know the hover state seemed suspect -- and good to delete, based on your comment. 

But did you also want me to delete the background color one for placeholder of tune comment. Sounded like there was some continuing use for that?

**Comment by rachelrosengoogle** [comment]
Changes look good! Thanks.

> But did you also want me to delete the background color one for placeholder of tune comment. Sounded like there was some continuing use for that?

Could you clarify which selector you're referring to? Is it the :host[tune-state="show"] > .--tune-placeholder.--tune-commentVisible one? If so, then, yes, I believe that one is fine to delete as well, since it means "a comment that has been revealed by the user when it was in a hidden state, and also not filtered by tune anymore," which I think is a rare state that can only be reached with that exact sequence of actions (if it can be reached at all...I haven't tested this recently!) Either way, I think it should be a no-op on the non-tuned state of the UI. If you want to be extra cautious, you can test it out with reddit and twitter, which are the only other places we change the background color for this element.

**Comment by JackHowa** [comment]
I fixed the ci error in #14 
Programming in a nutshell - Imgur

**Comment by JackHowa** [comment]
>  Is it the :host[tune-state="show"] > .--tune-placeholder.--tune-commentVisible one? If so, then, yes, 

Yep -- great.

**Comment by JackHowa** [comment]
Merged the latest from my other #14. Thanks for the quick approval @rachelrosengoogle!

**Pull request merged**
